[submit]
submit-node ansible_host=10.0.0.10 ansible_user=root

[manager]
central-manager ansible_host=10.0.0.11 ansible_user=root

[execute]
execute-node-1 ansible_host=10.0.0.12 ansible_user=root
execute-node-2 ansible_host=10.0.0.13 ansible_user=root

[storage]
nfs-server ansible_host=10.0.0.14 ansible_user=root

[monitoring-hosts]
monitoring ansible_host=10.0.0.15 ansible_user=root

[htcondor:children]
submit
manager
execute

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
