---
- name: Apply common configuration to all hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Configure NFS Server
  hosts: storage
  become: yes
  roles:
    - nfs-server

- name: Configure NFS Clients
  hosts: submit,manager,execute,observe
  become: yes
  roles:
    - nfs-client

- name: Configure HTCondor Central Manager
  hosts: manager
  become: yes
  roles:
    - htcondor-cm

- name: Configure HTCondor Submit Node
  hosts: submit
  become: yes
  roles:
    - htcondor-submit
    - docker
    - service-manager

- name: Configure HTCondor Execute Nodes
  hosts: execute
  become: yes
  roles:
    - htcondor-execute
    - apptainer
